version: "3.7"

services:
  php:
    container_name: php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - caddy
      - mysql
      - redis
    networks:
      - main

  caddy:
    container_name: caddy
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - main

  mysql:
    container_name: mysql
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - main

  redis:
    container_name: redis
    image: redis:latest
    networks:
      - main

networks:
  main:
    driver: bridge

volumes:
  dbdata:
