version: "3.8"

services:
  php:
    container_name: php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - nginx
      - database
      - redis
    networks:
      - main

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - ${NGINX_HTTP}:80
      - ${NGINX_HTTPS}:443
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - main

  database:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - main

  redis:
    image: redis:latest
    networks:
      - main

networks:
  main:
    driver: bridge

volumes:
  dbdata:
